# Python Tutorial for ML and Physics 2024
This tutorial is largely based on a tutorial by Lorenzo Cerrone and has been modified slightly by Peter Lippmann.

Ressources
 - http://www.scipy.org/topical-software.html


 Pro: 
 - efficient language: get stuff done with few lines 
 - readable 
 - popular in the scientific community
 - modules offer advanced algebraic, graphics, ... capabilities 
 - dynamically typed 
 - automatic memory management
 - open source, free 


 Contra: 
 - speed
 - many independent developers, thus heterogeneous modules and conventions
 - dynamically typed 
 - little used in mobile computing 

In [ ]:
print("Hello World")

## Basics of Jupyter

### shortcuts
- `ctrl + enter` or `shift + enter`: run code in a cell or run and go down one cell
- `ctrl + s`: save

### magics
- `[something]?`: shows the documentation of `[something]`
- `%timeit`, `%time`: to check the run time of a line
- `%%timeit`, `%%time`: to check the run time of a cell
- `%load_ext autoreload; %autoreload 2`: if you want to work on a local file 

# Data Types

## Numbers

In [ ]:
True, False                      # bool
10, 10_000, int('10')            # integers
10., 1e-4, float('1.3')          # floats (default is float64)
1 + 5j, complex(0, 1)            # complex

In [ ]:
a = 10
print(type(a))
a = float(a)
print(type(a))

## Strings

In [ ]:
'this is a string', "this is also a 'string'"

In [ ]:
b = 10/6
print(f'b is {b: .1f}')

## Lists

In [ ]:
[1, 2, 3], ['a', 'b', 1], [ [1, 0], [0, 1, 1] ]

In [ ]:
a = ['a', 2, 1]
a + [3, 4]
#a.remove(1)
# a.append(5)

## Dictionaries

In [ ]:
{'a': 1, 'b': [0, 0, 1]}, dict(a=1, b=[0, 0, 0])

In [ ]:
a = {'a': 1, 'b': 2}
a.update({'c': 1, 'a': 0})
a

## Sets and Tuples

In [ ]:
{1, 2, 2, 2, 1, 3}, (1, 2, 3)

a = {1, 2, 2, 3}
b = {2, 3}
a.union(b)

a = (1, 2, 3)

# Operations

## Number arithmetic

In [ ]:
2 + 2, 9 - 1, 3*4, 7 ** 2, 5/2, 5//2, 5%2

## Logical

In [ ]:
1 == 1, 2 > 1, 1 >= 1                       # all true
1 == 1 and True, True or False, not False   # all true
1 != 1, 1 < 1 < 2                           # all false

In [ ]:
1 < 1 and 1 < 3

# Controll flows

## If statement

In [ ]:
if 1 > 2:
    print('1 > 2')
    
elif 1 in [1, 2, 3]:
    print('1 in ..')
    
elif 1 not in [1, 2, 3]:
    print('1 not in ..')
    
else:
    print('False')

In [ ]:
a = [1, 2, 3]

if isinstance(a, list):
    print(a)

## For loops

In [ ]:
for i in range(1, 6, 2):
    print(i)
    
[i for i in range(5)]
{i: i**2 for i in range(5)}

a = ['a', 'b', 'c']
b = [1, 2, 3]
for value_a, value_b in zip(a, b):
    print(value_a, value_b)


In [ ]:
# indentation matters:
for i in (1, 2, 3): 
    print(i)
    print(i**2) # exponentiation

print('\n')
for i in (1, 2, 3): 
    print(i)
print(i**2) # exponentiation

## List comprehension

In [ ]:
print([a for a in range(5) if a % 2 == 0])

a = []
for i in range(5):
    if i > 2:
        a.append(i)
        
print(a)

## Functions and arguments unpacking

In [ ]:
a = 'global'
def sum_two_numbers(*args, **kwargs):
    ...
    a = 'local'
    print(a)
    return sum(args)

In [ ]:
sum_two_numbers(1, 2, 3, 6, 7, a=2, b=3)

## Classes and name spaces

In [ ]:
class Person:
    def __init__(self, name: str = 'Bob', age: int = 18):
        self.name = name
        self.age = age
        
    def after_one_year(self, how_many_years) -> None:
        x = 'inner test'
        self.age += how_many_years
        
bob = Person(name='Bob', age=20)
bob.after_one_year(10)
bob.age

# Advanced Topics

## Decorators and higher order functions

In [ ]:
import time

def function_timer(function):
    def new_function(*args, **kwarg):
        timer = time.time()
        result = function(*args, **kwarg)
        print("time taken", time.time() - timer)
        return result
    
    return new_function

@function_timer
def sum_two_numbers(a, b):
    return a + b

# alternative:
def old_function_timer(function, a, b):
    timer = time.time()
    function(a, b)
    print(time.time() - timer)

sum_two_numbers(1, 2) # how long does this take? 

## Dunder (double underscore) Methods
"If it walks like a duck and it quacks like a duck, then it must be a duck"

In [ ]:
class Postion:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __repr__(self):
        return f'position (x, y) {self.x, self.y}'
        
    def __add__(self, p):
        return Postion(self.x + p.x, self.y + p.y)

def add_positions(p1, p2):
    return Postion(p1.x + p2.x, p1.y + p2.y)

p1 = Postion(0, 1)
p2 = Postion(1, 0)
p3 = add_positions(p1, p2)
print(p3)
print(p1 + p2)

# Inheritance and the super method

In [ ]:
class Pet:
    def __init__(self, name: str, age: int):
        self.name = name
        self.age = age
        
    def __repr__(self):
        return f'{self.name} is a {self.age} years old'
    
class Dog(Pet):
    def __repr__(self):
        return super().__repr__() + ' Dog'

In [ ]:
Dog('Whisky', age=1)

# Numpy

In [ ]:
import numpy as np

## arrays

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6.])

# simple operations
# x.shape, x.reshape, astype indexing
x = x.reshape(2, 3)
x.astype('int64')
x.shape
x.max(), x.min(), x.argmax()
x.sum(), x.mean()
(x + 1) ** 2

## ufunc (universal functions) and functional style 

In [ ]:
a = [1, 1, 1]
b = a
b[0] = 0
a

In [ ]:
x = np.array([1, 1, 1])
y = x * 1
y[0] = 0
x, x is y

# when you need copy:

In [ ]:
x = np.array([1, 2, 3])
y = x 

x[0] = 0
print(y)  # y changed as well

x = np.array([1, 2, 3])
y = x.copy()

x[0] = 0
print(y)  # y did not change

## there are a lot more ufunc

In [ ]:
x = np.array([0.25, 0.5, 0.75])
# np.sin, np.log, np.sum, 
np.sin(x, out=x) # if you can avoid it 

## arrays initialization

In [ ]:
x = np.zeros((10, 10))
np.full((2, 2), 11), np.ones_like(x)

# random numbers

In [ ]:
np.random.rand() # uniform 0-1
np.random.randn() # gaussian dist. mean 0 std 1
np.random.randint(0, 3)

np.random.rand(10, 10).shape
np.random.randint(3, size=(10, 10))
list_x = ['a', 'b', 'c']
np.random.choice(list_x, size=2, replace=False)

## array - array operations

In [ ]:
x = np.random.rand(3)
y = np.random.rand(3)
# np.dot(x, y), x.dot(y), np.sum(x * y)
# x * y #element wise
np.dot(x, y), x.dot(y), np.sum(x * y)

In [ ]:
x = np.ones((3, 3))
#np.sum(x, axis=1)
x[0, :] = 0
print(x)
np.sum(x, axis=0), np.sum(x, axis=1)

In [ ]:
x = np.zeros(10)
x[None, :, np.newaxis].shape

## broadcasting example distance between array an point

In [39]:
x = np.random.rand(10, 3) # shape (10, 3)
x0 = np.random.rand(3) # shape (3, )
np.sqrt(np.sum((x - x0)**2, axis=1)) # l2 distance 

array([0.52686056, 0.76289213, 0.73613677, 0.62416794, 0.70033805,
       0.57240496, 0.57922235, 0.52653417, 0.6186059 , 0.64679325])

for more info https://numpy.org/doc/stable/user/basics.broadcasting.html

## advanced indexing and masking

In [41]:
x  = np.random.rand(10)
print(x)
mask = x > 0.5
print(mask)
x[mask]

[0.68772278 0.84923288 0.12956829 0.05490715 0.80948716 0.86052346
 0.21583288 0.88095884 0.56405965 0.46074438]
[ True  True False False  True  True False  True  True False]


array([0.68772278, 0.84923288, 0.80948716, 0.86052346, 0.88095884,
       0.56405965])

In [42]:
# np.where
np.where(x > 0.5, 1, 0)

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [ ]:
x[[0, 1, 2]]

## numpy linlang

In [43]:
matrix = np.random.rand(3, 3)

In [44]:
eig, eigvectors = np.linalg.eig(matrix)
print(eig)

[ 1.67119895  0.05889461 -0.37892882]


In [45]:
np.linalg.inv(matrix)

array([[15.08542706, -3.43515587, -0.46728906],
       [-9.73197104,  1.51065741,  1.95506762],
       [ 5.7561786 ,  0.3950215 , -1.65724627]])

In [46]:
np.matmul(np.linalg.inv(matrix), matrix)

array([[ 1.00000000e+00,  1.52261762e-16, -3.38300647e-16],
       [-1.03926249e-16,  1.00000000e+00, -8.02266582e-17],
       [ 1.64734816e-17,  2.52963073e-16,  1.00000000e+00]])

In [47]:
np.linalg.svd(matrix)

SVDResult(U=array([[-0.19790247, -0.0439971 , -0.97923382],
       [-0.73276668, -0.65689354,  0.17760595],
       [-0.65106652,  0.75269857,  0.09776125]]), S=array([1.67801859, 0.42788892, 0.05194377]), Vh=array([[-0.27526101, -0.76158105, -0.58670749],
       [ 0.53104817,  0.3882724 , -0.75314832],
       [-0.80138581,  0.5188823 , -0.29755997]]))

# numpy i/o

In [ ]:
np.save('test.npy', matrix)
np.load('test.npy')

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.arange(0, 12, 0.1)
y = np.sin(x)

In [ ]:
plt.figure(figsize=(10, 5))

plt.plot(x, y, c=np.random.rand(3), label='line')
plt.scatter(x[::10], y[::10], label='scatter')
plt.legend()
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.show()

In [ ]:
fig, axes = plt.subplots(1, 2)
axes[0].plot(x, y)
axes[1].plot(x, np.cos(x))
axes[1].set_xlabel('x')


In [ ]:
axes

In [ ]:
x, y = np.arange(-1, 1, 0.01), np.arange(-1, 1, 0.01)

"""
(-1, -1)......(-1, 1)
.
.
.
(1, -1) .......(1, 1)
"""

xx, yy = np.meshgrid(x, y)
zz = np.exp(- (xx)**2 - (yy)**2) 
zz.shape

In [ ]:
plt.imshow(zz, cmap='gray')
plt.colorbar()

https://matplotlib.org/devdocs/gallery/index.html

# Scipy

just too much to give an overview
https://scipy.github.io/devdocs/reference/cluster.html

## Scipy Example ODE

$\frac{d}{dt} x = - x^2 + 3$

In [ ]:
from scipy.integrate import odeint

def dx_dt(x, _):
    return - x**2 + 3

y_t = odeint(dx_dt, y0=1, t=np.arange(0, 3, 0.01))

plt.plot(np.arange(0, 3, 0.01), y_t)

## Scipy example convolutions

In [ ]:
from scipy.ndimage import convolve

image = np.zeros((50, 50))
image[20:-20, 20:-20] = 1
image += np.random.rand(*image.shape) * 0.2
plt.imshow(image)
plt.show()


smoothing_filter = np.ones((3, 3)) / 9
smooth_image = convolve(image, smoothing_filter)
plt.imshow(smooth_image)

## Scipy example fitting curve

In [ ]:
from scipy.optimize import curve_fit

def gaussian(x, sigma, mu):
    return np.exp(-(x - mu)**2/(2*sigma**2))

x = np.arange(-3, 3, 0.01)
y = gaussian(x, sigma=0.5, mu=1) + np.random.randn(*x.shape) * 0.1
plt.plot(x, y)

param, _ = curve_fit(gaussian, x, y)
param